### ISSUE TITLE
Is this project still under maintenance

### ISSUE THREAD

**Issue by Laffery** [java-json-tools/json-patch#152]
It seems that there are lots of issues and pull requests, but the last commit was 3 years ago

**Comment by BartekGravity** [comment]
Hey @Laffery, unfortunately it seems like this project is no longer maintained. However, we have decided to fork the repository and take over its maintenance. We are currently working on our first release. Hope this helps.

You can check it out here: https://github.com/gravity9-tech/json-patch-path

Cheers,
Bartek from gravity9

**Comment by Laffery** [comment]
> Hey @Laffery, unfortunately it seems like this project is no longer maintained. However, we have decided to fork the repository and take over its maintenance. We are currently working on our first release. Hope this helps.
> 
> You can check it out here: [gravity9-tech/json-patch-path](https://github.com/gravity9-tech/json-patch-path)
> 
> Cheers, Bartek from gravity9

LGTM. This library is the best one I could find so far to meet my needs, although there are still some things it can't do. Looking forward to your team releasing your first version!
