### ISSUE TITLE
Remove Guava dependency

### ISSUE THREAD

**Issue by lordofthejars** [java-json-tools/json-patch#18]
I know that it could imply a bit of work, but currently we would discard using this library because of Guava dependency. Not because we have nothing against Guava (in fact it is a really good library), but because we don't want to get a 2MB library when in fact only 2% of the whole library is being used. IMHO no general  library should use so big dependencies.

**Comment by daveclayton** [comment]
Perhaps we could consider this as part of work to split out the API as per discussion in issue #22

What do people think?

**Comment by Capstan** [comment]
Fixed in #66.

**Comment by asoldano** [comment]
@Capstan what are the plans wrt releasing a new version of json-patch (and required dep updates) including this guava removal? Any ETA?

**Comment by Capstan** [comment]
Since it eats about a workday to go through all these, I was planning to do another set of java-json-tools releases early Q2.

**Comment by asoldano** [comment]
I see, thanks, so that means 2-3 months from now I guess. Looking forward to that for inclusion in RESTEasy.
