### ISSUE TITLE
Integrate project with travis.

### ISSUE THREAD

**Issue by lordofthejars** [java-json-tools/json-patch#20]
Integrate project with travis so every time a PR or commit is sent, the whole project is tested in travis servers.

I can implement this as well.

**Comment by daveclayton** [comment]
Hi @lordofthejars I notice that Travis has a free licensing tier for Open Source repositories.

I'll take a look at this over the next week or so and will update here.

**Comment by daveclayton** [comment]
Hi @lordofthejars found time to look at this tonight, and have set up the 3 projects in Travis.  Great idea.

Let me know if this covers everything you had in mind - I'll close the ticket on Friday 15th July if I don't hear back from you by then.

**Comment by Capstan** [comment]
Fixed in commit c1a9abd
